repos:
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        name: nbstripout
        description: "Strip output from Jupyter and IPython notebooks"
        files: ".ipynb$" 