# Generated by Django 5.2.5 on 2025-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('pert_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pert_iname', models.CharField(max_length=100)),
                ('pert_type', models.CharField(blank=True, max_length=50, null=True)),
                ('moa', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compound',
                'verbose_name_plural': 'Compounds',
            },
        ),
    ]
