# Generated by Django 5.2.5 on 2025-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('cell_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cell_name', models.CharField(max_length=100)),
                ('cell_source', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cell Line',
                'verbose_name_plural': 'Cell Lines',
            },
        ),
    ]
