# Generated by Django 5.2.5 on 2025-08-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0002_cellline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellline',
            old_name='cell_source',
            new_name='cell_lineage',
        ),
        migrations.RemoveField(
            model_name='cellline',
            name='cell_name',
        ),
        migrations.AddField(
            model_name='cellline',
            name='growth_pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cellline',
            name='primary_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='cell_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='cell_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('sig_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tas', models.FloatField(blank=True, null=True)),
                ('ss_ngene', models.IntegerField(blank=True, null=True)),
                ('distil_cc_q75', models.FloatField(blank=True, null=True)),
                ('pert_dose', models.FloatField(blank=True, null=True)),
                ('pert_dose_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('pert_time', models.FloatField(blank=True, null=True)),
                ('pert_time_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('is_exemplar_sig', models.BooleanField(default=False)),
                ('is_null_sig', models.BooleanField(default=False)),
                ('is_ncs_sig', models.BooleanField(default=False)),
                ('qc_pass', models.BooleanField(default=True)),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='lincs.cellline')),
                ('pert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='lincs.compound')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
    ]
