# Generated by Django 5.2.5 on 2025-08-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0003_rename_cell_source_cellline_cell_lineage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('plate_id', models.CharField(max_length=50)),
                ('well_id', models.CharField(max_length=10)),
                ('count_mean', models.FloatField(blank=True, null=True)),
                ('count_cv', models.FloatField(blank=True, null=True)),
                ('qc_f_logp', models.FloatField(blank=True, null=True)),
                ('qc_iqr', models.FloatField(blank=True, null=True)),
                ('qc_slope', models.FloatField(blank=True, null=True)),
                ('qc_pass', models.BooleanField()),
                ('dyn_range', models.FloatField(blank=True, null=True)),
                ('inv_level_10', models.FloatField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cmap_name', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='lincs.signature')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'indexes': [models.Index(fields=['instance_id'], name='lincs_insta_instanc_28a336_idx'), models.Index(fields=['plate_id'], name='lincs_insta_plate_i_1cfaf9_idx')],
            },
        ),
    ]
