# Generated by Django 5.2.5 on 2025-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0004_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('ensembl_id', models.CharField(blank=True, max_length=30, null=True)),
                ('gene_title', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_type', models.CharField(blank=True, max_length=50, null=True)),
                ('src', models.CharField(blank=True, max_length=20, null=True)),
                ('feature_space', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
            },
        ),
    ]
