# Generated by Django 5.2.5 on 2025-08-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0005_gene'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lincs.gene')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lincs.signature')),
            ],
            options={
                'verbose_name': 'Expression Matrix Entry',
                'verbose_name_plural': 'Expression Matrix Entries',
                'indexes': [models.Index(fields=['gene'], name='lincs_expre_gene_id_38de88_idx'), models.Index(fields=['signature'], name='lincs_expre_signatu_51d3b9_idx')],
            },
        ),
    ]
