# Generated by Django 5.2.5 on 2025-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincs', '0006_expressionmatrixentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='pert_iname',
            new_name='cmap_name',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='pert_type',
        ),
        migrations.AddField(
            model_name='compound',
            name='canonical_smiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_aliases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='inchi_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
    ]
